data_ingestion: 
  source: "azure_blob" 
  container_name: "data" 
  blob_name: "archive.zip" 
  raw_data_dir: "data/raw_data"
  extract_dir: "data/raw_data"

data_validation:
  annotations_dir: "data/raw_data/annotations"
  images_dir: "data/raw_data/images"
  required_classes: 
    - "With Helmet"
    - "Without Helmet"


